import type { Project, Developer, Comment, Service } from "./types"
import { calculateEarnedBadges } from "./reputation"

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "DeFi Lending Protocol",
    description:
      "A decentralized lending protocol built on Arcnet with optimized gas costs and advanced risk management. Features include multi-collateral support, dynamic interest rates, and flash loans.",
    stack: ["Solidity", "Next.js", "Ethers.js", "Hardhat"],
    githubUrl: "https://github.com/example/defi-lending",
    imageUrl: "/defi-lending-protocol-dashboard.jpg",
    tags: ["defi", "lending", "arcnet", "smart-contracts"],
    ipfsHash: "QmX7Y8Z9...",
    author: "Alice Dev",
    authorAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
    createdAt: Date.now() - 86400000 * 5,
    upvotes: 42,
    commentCount: 12,
  },
  {
    id: "2",
    title: "NFT Marketplace",
    description:
      "Full-featured NFT marketplace with lazy minting, royalties, and auction functionality. Built with modern Web3 standards and optimized for Arcnet network.",
    stack: ["Rust", "React", "TypeScript", "IPFS"],
    githubUrl: "https://github.com/example/nft-marketplace",
    imageUrl: "/nft-marketplace-interface.png",
    tags: ["nft", "marketplace", "web3", "arcnet"],
    ipfsHash: "QmA1B2C3...",
    author: "Bob Builder",
    authorAddress: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
    createdAt: Date.now() - 86400000 * 3,
    upvotes: 35,
    commentCount: 8,
  },
  {
    id: "3",
    title: "DAO Governance Platform",
    description:
      "Complete DAO governance solution with proposal creation, voting mechanisms, and treasury management. Supports token-weighted voting and delegation.",
    stack: ["Solidity", "Vue.js", "Web3.js", "Foundry"],
    githubUrl: "https://github.com/example/dao-governance",
    imageUrl: "/dao-governance-voting-interface.jpg",
    tags: ["dao", "governance", "voting", "defi"],
    ipfsHash: "QmD4E5F6...",
    author: "Charlie Chain",
    authorAddress: "0x1234567890123456789012345678901234567890",
    createdAt: Date.now() - 86400000 * 7,
    upvotes: 28,
    commentCount: 15,
  },
  {
    id: "4",
    title: "Cross-Chain Bridge",
    description:
      "Secure cross-chain bridge connecting Arcnet with other major networks. Features automated liquidity management and minimal slippage.",
    stack: ["Solidity", "Go", "Next.js", "Chainlink"],
    githubUrl: "https://github.com/example/cross-chain-bridge",
    imageUrl: "/blockchain-bridge-transfer-interface.jpg",
    tags: ["bridge", "cross-chain", "defi", "arcnet"],
    ipfsHash: "QmG7H8I9...",
    author: "Diana Dev",
    authorAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    createdAt: Date.now() - 86400000 * 2,
    upvotes: 51,
    commentCount: 20,
  },
  {
    id: "5",
    title: "Decentralized Identity System",
    description:
      "Self-sovereign identity solution for Web3. Users control their credentials and share them selectively with zero-knowledge proofs.",
    stack: ["Rust", "React", "IPFS", "Circom"],
    githubUrl: "https://github.com/example/decentralized-identity",
    imageUrl: "/digital-identity-verification-dashboard.jpg",
    tags: ["identity", "privacy", "zk-proofs", "web3"],
    ipfsHash: "QmJ1K2L3...",
    author: "Eve Explorer",
    authorAddress: "0x9876543210987654321098765432109876543210",
    createdAt: Date.now() - 86400000 * 1,
    upvotes: 19,
    commentCount: 6,
  },
  {
    id: "6",
    title: "Social Token Launchpad",
    description:
      "Platform for creators to launch and manage their social tokens. Includes bonding curves, staking, and community governance features.",
    stack: ["Solidity", "Svelte", "Ethers.js", "The Graph"],
    githubUrl: "https://github.com/example/social-token-launchpad",
    imageUrl: "/token-launch-platform-analytics.jpg",
    tags: ["social-tokens", "creator-economy", "defi", "arcnet"],
    ipfsHash: "QmM4N5O6...",
    author: "Frank Founder",
    authorAddress: "0x1111111111111111111111111111111111111111",
    createdAt: Date.now() - 86400000 * 4,
    upvotes: 33,
    commentCount: 11,
  },
]

export const MOCK_DEVELOPERS: Developer[] = [
  {
    address: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
    name: "Alice Dev",
    bio: "Full-stack Web3 developer specializing in DeFi protocols and smart contract security. 5+ years building on Ethereum and Arcnet.",
    stack: ["Solidity", "Next.js", "Ethers.js", "Hardhat", "React", "TypeScript"],
    socialLinks: {
      github: "https://github.com/alicedev",
      twitter: "https://twitter.com/alicedev",
      website: "https://alicedev.io",
      nostr: "npub1alice...",
    },
    profileHash: "QmAlice123...",
    reputation: 1250,
    projectsPublished: 12,
    solutionsAccepted: 45,
    servicesCompleted: 8,
    joinedAt: Date.now() - 86400000 * 365,
    badges: [],
  },
  {
    address: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
    name: "Bob Builder",
    bio: "NFT and blockchain gaming expert. Creating next-gen Web3 experiences with focus on user experience and scalability.",
    stack: ["Rust", "React", "TypeScript", "IPFS", "Solana", "Anchor"],
    socialLinks: {
      github: "https://github.com/bobbuilder",
      twitter: "https://twitter.com/bobbuilder",
    },
    profileHash: "QmBob456...",
    reputation: 980,
    projectsPublished: 8,
    solutionsAccepted: 32,
    servicesCompleted: 15,
    joinedAt: Date.now() - 86400000 * 280,
    badges: [],
  },
  {
    address: "0x1234567890123456789012345678901234567890",
    name: "Charlie Chain",
    bio: "DAO and governance specialist. Building tools for decentralized communities and transparent decision-making systems.",
    stack: ["Solidity", "Vue.js", "Web3.js", "Foundry", "The Graph"],
    socialLinks: {
      github: "https://github.com/charliechain",
      website: "https://charliechain.dev",
      nostr: "npub1charlie...",
    },
    profileHash: "QmCharlie789...",
    reputation: 1420,
    projectsPublished: 15,
    solutionsAccepted: 67,
    servicesCompleted: 12,
    joinedAt: Date.now() - 86400000 * 420,
    badges: [],
  },
  {
    address: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    name: "Diana Dev",
    bio: "Cross-chain infrastructure developer. Passionate about interoperability and building bridges between blockchain ecosystems.",
    stack: ["Solidity", "Go", "Next.js", "Chainlink", "Rust"],
    socialLinks: {
      github: "https://github.com/dianadev",
      twitter: "https://twitter.com/dianadev",
      website: "https://diana.dev",
    },
    profileHash: "QmDiana101...",
    reputation: 1680,
    projectsPublished: 18,
    solutionsAccepted: 89,
    servicesCompleted: 22,
    joinedAt: Date.now() - 86400000 * 500,
    badges: [],
  },
]

MOCK_DEVELOPERS.forEach((dev) => {
  dev.badges = calculateEarnedBadges(dev)
})

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c1",
    projectId: "1",
    author: "Bob Builder",
    authorAddress: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
    content:
      "Great project! I'm trying to integrate this with my NFT marketplace. How do you handle flash loan attacks?",
    createdAt: Date.now() - 86400000 * 2,
    upvotes: 8,
    isAcceptedSolution: false,
    replies: [
      {
        id: "c1-r1",
        projectId: "1",
        author: "Alice Dev",
        authorAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
        content:
          "Thanks! We use a combination of reentrancy guards and flash loan fee mechanisms. Check out the FlashLoanProtection.sol contract in the repo for implementation details.",
        createdAt: Date.now() - 86400000 * 2 + 3600000,
        upvotes: 12,
        isAcceptedSolution: true,
        replies: [],
      },
    ],
  },
  {
    id: "c2",
    projectId: "1",
    author: "Charlie Chain",
    authorAddress: "0x1234567890123456789012345678901234567890",
    content: "What's the gas cost for a typical borrow/lend transaction on Arcnet?",
    createdAt: Date.now() - 86400000 * 1,
    upvotes: 5,
    isAcceptedSolution: false,
    replies: [
      {
        id: "c2-r1",
        projectId: "1",
        author: "Alice Dev",
        authorAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
        content:
          "On Arcnet, a borrow transaction costs around 120k gas and lending is about 85k gas. Much cheaper than Ethereum mainnet!",
        createdAt: Date.now() - 86400000 * 1 + 7200000,
        upvotes: 6,
        isAcceptedSolution: true,
        replies: [],
      },
    ],
  },
  {
    id: "c3",
    projectId: "1",
    author: "Diana Dev",
    authorAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    content: "Is there a way to add custom collateral types? I'd like to support LP tokens from my DEX.",
    createdAt: Date.now() - 3600000 * 12,
    upvotes: 3,
    isAcceptedSolution: false,
    replies: [],
  },
  {
    id: "c4",
    projectId: "2",
    author: "Alice Dev",
    authorAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
    content: "Does this support ERC-1155 tokens or just ERC-721?",
    createdAt: Date.now() - 86400000 * 1,
    upvotes: 4,
    isAcceptedSolution: false,
    replies: [
      {
        id: "c4-r1",
        projectId: "2",
        author: "Bob Builder",
        authorAddress: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
        content: "Currently only ERC-721, but ERC-1155 support is coming in v2! Follow the GitHub for updates.",
        createdAt: Date.now() - 86400000 * 1 + 1800000,
        upvotes: 5,
        isAcceptedSolution: true,
        replies: [],
      },
    ],
  },
]

export const MOCK_SERVICES: Service[] = [
  {
    id: "s1",
    title: "Smart Contract Security Audit",
    description:
      "Comprehensive security audit of your smart contracts including automated testing, manual review, and detailed report. Experienced with DeFi protocols, NFT contracts, and governance systems.",
    category: "Audit",
    price: "2.5 ARC",
    duration: "1-2 weeks",
    stack: ["Solidity", "Hardhat", "Slither", "Mythril"],
    provider: "Alice Dev",
    providerAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
    createdAt: Date.now() - 86400000 * 10,
    rating: 4.9,
    completedJobs: 23,
  },
  {
    id: "s2",
    title: "Full-Stack DApp Development",
    description:
      "End-to-end Web3 application development from smart contracts to responsive frontend. Specialized in React, Next.js, and modern Web3 libraries. Includes deployment and documentation.",
    category: "Development",
    price: "8 ARC",
    duration: "3-4 weeks",
    stack: ["Solidity", "Next.js", "React", "Ethers.js", "TypeScript"],
    provider: "Bob Builder",
    providerAddress: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
    createdAt: Date.now() - 86400000 * 5,
    rating: 4.8,
    completedJobs: 15,
  },
  {
    id: "s3",
    title: "DAO Setup & Configuration",
    description:
      "Complete DAO infrastructure setup including governance contracts, voting mechanisms, treasury management, and member management. Customized to your community needs.",
    category: "Consulting",
    price: "3.5 ARC",
    duration: "2-3 weeks",
    stack: ["Solidity", "Snapshot", "The Graph", "IPFS"],
    provider: "Charlie Chain",
    providerAddress: "0x1234567890123456789012345678901234567890",
    createdAt: Date.now() - 86400000 * 15,
    rating: 5.0,
    completedJobs: 18,
  },
  {
    id: "s4",
    title: "Cross-Chain Bridge Integration",
    description:
      "Integrate cross-chain functionality into your DApp. Support for multiple chains, automated liquidity management, and secure asset transfers with minimal slippage.",
    category: "Integration",
    price: "5 ARC",
    duration: "2-3 weeks",
    stack: ["Solidity", "Go", "Chainlink", "LayerZero"],
    provider: "Diana Dev",
    providerAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    createdAt: Date.now() - 86400000 * 3,
    rating: 4.9,
    completedJobs: 12,
  },
  {
    id: "s5",
    title: "NFT Collection Launch",
    description:
      "Complete NFT project setup including smart contract development, metadata generation, IPFS hosting, minting website, and marketplace integration. Includes rarity system.",
    category: "Development",
    price: "4 ARC",
    duration: "2 weeks",
    stack: ["Solidity", "React", "IPFS", "Pinata"],
    provider: "Bob Builder",
    providerAddress: "0x8e23Ee67d1332aD560396262C48ffbB273f626E1",
    createdAt: Date.now() - 86400000 * 7,
    rating: 4.8,
    completedJobs: 15,
  },
  {
    id: "s6",
    title: "Gas Optimization Consultation",
    description:
      "Optimize your smart contracts for lower gas costs. Includes code review, refactoring recommendations, and implementation support. Average 30-40% gas savings.",
    category: "Consulting",
    price: "1.5 ARC",
    duration: "3-5 days",
    stack: ["Solidity", "Foundry", "Hardhat"],
    provider: "Alice Dev",
    providerAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb1",
    createdAt: Date.now() - 86400000 * 12,
    rating: 4.9,
    completedJobs: 23,
  },
]
